-- Step 1: Create OrderStatus enum type
DO $$ BEGIN
    CREATE TYPE "OrderStatus" AS ENUM ('PENDING', 'PROCESSING', 'SHIPPED', 'DELIVERED', 'CANCELLED');
EXCEPTION
    WHEN duplicate_object THEN null;
END $$;

-- Step 2: Drop any existing tables to start clean
DROP TABLE IF EXISTS "CartItem";
DROP TABLE IF EXISTS "Product";
DROP TABLE IF EXISTS "Order";

-- Step 3: Create Product table first (no foreign key dependencies)
CREATE TABLE "Product" (
  "id" BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  "name" TEXT NOT NULL,
  "description" TEXT NOT NULL,
  "price" DECIMAL(10, 2) NOT NULL,
  "image" TEXT,
  "category" TEXT NOT NULL,
  "inventory" INTEGER NOT NULL DEFAULT 0,
  "createdAt" TIMESTAMP NOT NULL DEFAULT NOW(),
  "updatedAt" TIMESTAMP NOT NULL DEFAULT NOW()
);

-- Step 4: Create Order table (no foreign key dependencies)
CREATE TABLE "Order" (
  "id" BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  "total" DECIMAL(10, 2) NOT NULL,
  "status" "OrderStatus" NOT NULL DEFAULT 'PENDING',
  "customerEmail" TEXT NOT NULL,
  "customerName" TEXT NOT NULL,
  "shippingAddress" TEXT NOT NULL,
  "createdAt" TIMESTAMP NOT NULL DEFAULT NOW(),
  "updatedAt" TIMESTAMP NOT NULL DEFAULT NOW(),
  "stripePaymentIntentId" TEXT UNIQUE
);

-- Step 5: Create CartItem table (has foreign key dependencies to Product and Order)
CREATE TABLE "CartItem" (
  "id" BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  "quantity" INTEGER NOT NULL,
  "productId" BIGINT NOT NULL,
  "orderId" BIGINT,
  "createdAt" TIMESTAMP NOT NULL DEFAULT NOW(),
  "updatedAt" TIMESTAMP NOT NULL DEFAULT NOW()
);

-- Step 6: Add foreign key constraints after all tables exist
ALTER TABLE "CartItem" 
  ADD CONSTRAINT "CartItem_productId_fkey" 
  FOREIGN KEY ("productId") REFERENCES "Product"("id") ON DELETE RESTRICT;

ALTER TABLE "CartItem" 
  ADD CONSTRAINT "CartItem_orderId_fkey" 
  FOREIGN KEY ("orderId") REFERENCES "Order"("id") ON DELETE SET NULL;

-- Step 7: Create indexes
CREATE INDEX "CartItem_productId_idx" ON "CartItem"("productId");
CREATE INDEX "CartItem_orderId_idx" ON "CartItem"("orderId");

-- Step 8: Insert sample products
INSERT INTO "Product" ("name", "description", "price", "image", "category", "inventory", "createdAt", "updatedAt") VALUES
  ('Organic Cotton T-Shirt', 'A soft, comfortable t-shirt made from 100% organic cotton.', 29.99, '/images/products/tshirt.jpg', 'clothing', 100, NOW(), NOW()),
  ('Ceramic Coffee Mug', 'Handcrafted ceramic coffee mug with a unique glazed finish.', 19.99, '/images/products/mug.jpg', 'home', 50, NOW(), NOW()),
  ('Wireless Bluetooth Headphones', 'Premium noise-cancelling headphones with 20-hour battery life.', 129.99, '/images/products/headphones.jpg', 'electronics', 25, NOW(), NOW()),
  ('Leather Wallet', 'Genuine leather wallet with multiple card slots and RFID protection.', 49.99, '/images/products/wallet.jpg', 'accessories', 75, NOW(), NOW()),
  ('Stainless Steel Water Bottle', 'Double-walled insulated water bottle that keeps drinks cold for 24 hours.', 34.99, '/images/products/bottle.jpg', 'home', 60, NOW(), NOW()),
  ('Organic Scented Candle', 'Hand-poured soy wax candle with essential oils and a 40-hour burn time.', 24.99, '/images/products/candle.jpg', 'home', 40, NOW(), NOW());